
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Aug 24 02:19:40 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 25;
  public static final int CHAR = 48;
  public static final int CONST = 6;
  public static final int NOTEQUAL = 18;
  public static final int LPAREN = 37;
  public static final int GREATER = 20;
  public static final int SEMI = 33;
  public static final int CONTINUE = 15;
  public static final int LESS = 22;
  public static final int MINUS = 24;
  public static final int RPAREN = 38;
  public static final int LESSEQUAL = 21;
  public static final int BOOL = 49;
  public static final int COMMA = 35;
  public static final int CLASS = 4;
  public static final int EQUALEQUAL = 17;
  public static final int DIV = 29;
  public static final int PIPEPIPE = 31;
  public static final int PLUS = 23;
  public static final int IF = 7;
  public static final int DOT = 36;
  public static final int FINDANY = 44;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 26;
  public static final int RETURN = 12;
  public static final int EQUAL = 27;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int NUMBER = 46;
  public static final int MOD = 30;
  public static final int IDENT = 47;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int LBRACK = 41;
  public static final int GREATEREQUAL = 19;
  public static final int ARROW = 43;
  public static final int FOREACH = 16;
  public static final int COLON = 34;
  public static final int LBRACE = 39;
  public static final int ELSE = 5;
  public static final int RBRACK = 42;
  public static final int READ = 11;
  public static final int WHILE = 8;
  public static final int AMPAMP = 32;
  public static final int RBRACE = 40;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int PRINT = 10;
  public static final int FINDANDREPLACE = 45;
}

