
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jul 19 23:12:50 CEST 2023
//----------------------------------------------------
package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old { //sym je malim slovima da bi bilo kompatibilno sa generatorom parsera u sl fazi
	//klasa u kojoj cuvam identifikatore
	//sama ce se generisati u sledecoj fazi razvoja kompajlera
	//prvo rucno pisemo sadrzaj te klase a onda cemo je u sledecoj fazi obrisati
	//Keywords
	public static final int PROG=1;
	public static final int BREAK=2;
	public static final int CLASS=3;
	public static final int ELSE=4;
	public static final int CONST=5;
	public static final int IF=6;
	public static final int WHILE=7;
	public static final int NEW=8;
	public static final int PRINT=9;
	public static final int READ=10;
	public static final int RETURN=11;
	public static final int VOID=12; //za metode koje nemaju povratnu vrednost
	public static final int EXTENDS=13;
	public static final int CONTINUE=14;
	public static final int FOREACH=15;
	
	//Identifiers
	public static final int IDENT=16;
	
	//Constants
	public static final int NUMBER=17;
	public static final int CHAR=18;
	public static final int BOOL=19;
	
	
	//Operators
	public static final int EQUALEQUAL=20;
	public static final int NOTEQUAL=21;
	public static final int GREATEREQUAL=22;
	public static final int GREATER=23;
	public static final int LESSEQUAL=24;
	public static final int LESS=25;
	public static final int PLUS=26;
	public static final int MINUS=27;
	public static final int PLUSPLUS=28;
	public static final int MINUSMINUS=29;
	public static final int EQUAL=30;
	public static final int MUL=31;
	public static final int DIV=32;
	public static final int MOD=33;
	public static final int PIPEPIPE=34;
	public static final int AMPAMP=35;
	public static final int SEMI=36;
	public static final int COLON=37;
	public static final int COMMA=38;
	public static final int DOT=39;
	public static final int LPAREN=40;
	public static final int RPAREN=41;
	public static final int LBRACE=42;
	public static final int RBRACE=43;
	public static final int LBRACK=44;
	public static final int RBRACK=45;
	public static final int ARROW=46;

	//Ostalo
	public static final int EOF=0;
	public static final int error = -1;
	public static final int FINDANY=47;
	public static final int FINDANDREPLACE = 48;
}

